version: '3.8'

services:
  coral:
    build: .
    volumes:
      - ./pycoral:/workspace
    environment:
      - PYTHONPATH=/usr/lib/python3/dist-packages
      - LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu
    devices:
      - "/dev/bus/usb/002/003:/dev/bus/usb/002/003"
    command: [ "/bin/bash", "-c", "tail -f /dev/null" ]
